# Build environment for the application
FROM raveious/fastrtps:alpine-latest as builder

# Install build dependences
RUN apk add --update --no-cache git cmake make build-base gcc g++ linux-headers openssl openssl-dev boost boost-dev zlib-dev

# Build cpprestsdk
RUN git clone --depth 1 --recurse-submodules --single-branch https://github.com/Microsoft/cpprestsdk.git /cpprestsdk
WORKDIR /cpprestsdk/build
RUN cmake .. && make && make install

WORKDIR /build
