version: '3.1'

services:
  weather_forcaster:
    image: raveious/darksky-rtps
    ports:
      - '44084:44084'
      - '17900:17900'
      - '17910:17910'
      - '17911:17911'
    secrets:
      - DARKSKY_KEY
      - DARKSKY_LATITUDE
      - DARKSKY_LONGITUDE

secrets:
  DARKSKY_KEY:
    external: true
  DARKSKY_LATITUDE:
    external: true
  DARKSKY_LONGITUDE:
    external: true

